### ISSUE TITLE
Missing required parameter 'digestmod'.

### ISSUE THREAD

**Issue by vic-t** [vic-t/erpitst#8]
Der Versand gewisser einzelner Emails schlägt fehlt mit der oben angegebenen Fehlermeldung. 

 App Versions
```
{
	"erpnext": "12.1.6",
	"erpnextswiss": "1.15.0",
	"frappe": "12.0.16",
	"itst": "0.0.1"
}
```
Route
```
Form/Email Queue/c390b62fa4
Error Report
```
Traceback (most recent call last):
```
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 60, in application
    response = frappe.api.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 56, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1036, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_queue/email_queue.py", line 45, in send_now
    send_one(name, now=True)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/queue.py", line 468, in send_one
    raise e
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/queue.py", line 406, in send_one
    message = prepare_message(email, recipient.recipient, recipients_list)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/queue.py", line 489, in prepare_message
    unsubscribe_url = get_unsubcribed_url(email.reference_doctype, email.reference_name, recipient,
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/queue.py", line 289, in get_unsubcribed_url
    query_string = get_signed_params(params)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/verified_command.py", line 20, in get_signed_params
    signature = hmac.new(params.encode())
  File "/usr/lib/python3.8/hmac.py", line 153, in new
    return HMAC(key, msg, digestmod)
  File "/usr/lib/python3.8/hmac.py", line 51, in __init__
    raise TypeError("Missing required parameter 'digestmod'.")
TypeError: Missing required parameter 'digestmod'.
```
Request Data
```
{
	"type": "POST",
	"args": {
		"name": "f2b1b26fbe"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.email.doctype.email_queue.email_queue.send_now"
}
```
Response JSON
`{}`

**Comment by vic-t** [comment]
hmac.py scheint in Python 3.8 so verändert worden zu sein, dass der Parameter digestmod zwingend gesetzt sein muss. Folgende Module, welche womöglich in ERPnext zum Einsatz kommen, greifen auf diese Library zu: 

ldap3 (Kompatibilität ab 2.6 gewährleistet)
impacket (Kompatibilität ab 0.9.22 gewährleistet)

**Comment by vic-t** [comment]
```
$ env/bin/pip show ldap3
Name: ldap3
Version: 2.9.1
Summary: A strictly RFC 4510 conforming LDAP V3 pure Python client library
Home-page: https://github.com/cannatag/ldap3
Author: Giovanni Cannata
Author-email: cannatag@gmail.com
License: LGPL v3
Location: /home/frappe/frappe-bench/env/lib/python3.8/site-packages
Requires: pyasn1
Required-by: impacket, ldapdomaindump

$ env/bin/pip show impacket
Name: impacket
Version: 0.9.24
Summary: Network protocols Constructors and Dissectors
Home-page: https://www.secureauth.com/labs/open-source-tools/impacket
Author: SecureAuth Corporation
Author-email: oss@secureauth.com
License: Apache modified
Location: /home/frappe/frappe-bench/env/lib/python3.8/site-packages
Requires: chardet, flask, future, ldap3, ldapdomaindump, pyasn1, pycryptodomex, pyOpenSSL, six
Required-by: 
```

**Comment by lasalesi** [comment]
updated source to fix this compatibility issue in Py3.8
